version: '2'

vars:
  OWNER: eiskye
  SERVICE: art-gamemode

tasks:
  local:
    cmds:
      - sampctl package run --forceBuild

  # -
  # Docker
  # -

  build:
    cmds:
      - docker build --no-cache --tag {{.OWNER}}/{{.SERVICE}}:1.0 .

  run:
    cmds:
      - docker run {{.OWNER}}/{{.SERVICE}}:1.0

  push:
    cmds:
      - docker push {{.OWNER}}/{{.SERVICE}}:1.0